src/Inei/Bundle/AuthBundle/Entity/Usuarios.php
<?php

// src/Acme/UserBundle/Entity/User.php

namespace Inei\Bundle\AuthBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Inei\Bundle\AuthBundle\Entity\User
 *
 * @ORM\Table(name="USUARIOS",
 * indexes={@ORM\Index(name="NOM_COMP_USU_idx", columns={"NOM_COMP_USU"})})
 * @ORM\Entity(repositoryClass="Inei\Bundle\AuthBundle\Repository\UsuariosRepository")
 */
class Usuarios implements AdvancedUserInterface, \Serializable {

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="NOM_COMP_USU", type="string", length=150)
     */
    private $nombres;

    /**
     * @ORM\Column(name="COD_USU", type="string", length=25, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(name="SALT_USU", type="string", length=32)
     */
    private $salt;

    /**
     * @ORM\Column(name="PASS_USU", type="string", length=128)
     */
    private $password;

    /**
     * @ORM\Column(name="EMAIL_USU", type="string", length=60, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\ManyToMany(targetEntity="Role", inversedBy="users")
     *
     */
    private $roles;
    
    private $permissions;

    public function getRoles() {
        $roles = $this->roles->toArray();
        $roles[] = 'ROLE_USER';
        return $roles;
    }
    
    public function __toString() {
        return $this->username;
    }

    public function __construct() {
        $this->isActive = true;
        $this->salt = md5(uniqid(null, true));
        $this->roles = new ArrayCollection();
    }

    public function eraseCredentials() {
        
    }

    public function getPassword() {
        return $this->password;
    }

//    public function getRoles() {
//        return array('ROLE_ADMIN');
//    }

    public function getSalt() {
        return '';
    }

    public function getUsername() {
        return $this->username;
    }

    /**
     * @see \Serializable::serialize()
     */
    public function serialize() {
        return serialize(array(
            $this->id,
        ));
    }

    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized) {
        list (
                $this->id,
                ) = unserialize($serialized);
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set nombres
     *
     * @param string $nombres
     * @return Usuarios
     */
    public function setNombres($nombres) {
        $this->nombres = $nombres;

        return $this;
    }

    /**
     * Get nombres
     *
     * @return string 
     */
    public function getNombres() {
        return $this->nombres;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return Usuarios
     */
    public function setUsername($username) {
        $this->username = $username;

        return $this;
    }

    /**
     * Set salt
     *
     * @param string $salt
     * @return Usuarios
     */
    public function setSalt($salt) {
        $this->salt = $salt;

        return $this;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return Usuarios
     */
    public function setPassword($password) {
        $this->password = $password;

        return $this;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Usuarios
     */
    public function setEmail($email) {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return Usuarios
     */
    public function setIsActive($isActive) {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function isActive() {
        return $this->isActive;
    }

    public function isAccountNonExpired() {
        return true;
    }

    public function isAccountNonLocked() {
        return true;
    }

    public function isCredentialsNonExpired() {
        return true;
    }

    public function isEnabled() {
        return $this->isActive();
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive() {
        return $this->isActive;
    }

    /**
     * Add roles
     *
     * @param \Inei\Bundle\AuthBundle\Entity\Role $roles
     * @return Usuarios
     */
    public function addRole(\Inei\Bundle\AuthBundle\Entity\Role $roles) {
        $this->roles[] = $roles;

        return $this;
    }

    /**
     * Remove roles
     *
     * @param \Inei\Bundle\AuthBundle\Entity\Role $roles
     */
    public function removeRole(\Inei\Bundle\AuthBundle\Entity\Role $roles) {
        $this->roles->removeElement($roles);
    }

    public function getRolesCollection() {
        return $this->roles;
    }
    
    public function getActiveDisplay(){
        return $this->isActive ? 'ACTIVO' : 'INACTIVO';
    }
    
    public function setPermissions(array $permissions){
        $this->permissions = $permissions;
        
        return $this;
    }
    
    public function getPermissions(){
        return $this->permissions;
    }

}

src/Inei/Bundle/AuthBundle/Controller/SecurityCrudController.php
<?php

namespace Inei\Bundle\AuthBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Inei\Bundle\AuthBundle\Entity\Usuarios;
use Inei\Bundle\AuthBundle\Entity\Role;

/**
 * Description of SecurityCrudController
 *
 * @author holivares
 */
class SecurityCrudController extends Controller {

    /**
     * @Route("/user", name="_admin_user_list")
     * @Template("")     
     */
    public function listUserAction(Request $request) {
        if (!$this->get('usuario_service')->hasPermission('usuario', 'query')) {
            throw $this->createNotFoundException();
        }
        $form = $this->createForm('usuario_search');
        $form->handleRequest($request);
        $criteria = $form->getData() ? $form->getData() : array();
        foreach ($criteria as $key => $value) {
            if (!$value) {
                unset($criteria[$key]);
            }
        }
        $em = $this->getDoctrine()
                ->getRepository('IneiAuthBundle:Usuarios');
        $query = $em->findUsingLike($criteria);
        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $query, $this->get('request')->query->get('page', 1)/* page number */, 15/* limit per page */
        );


        return array(
            'pagination' => $pagination,
            'form' => $form->createView()
        );
    }

    /**
     * @Route("/user/add", name="_admin_user_add")
     * @Template("")
     */
    public function addUserAction(Request $request) {
        if (!$this->get('usuario_service')->hasPermission('usuario', 'add')) {
            throw $this->createNotFoundException();
        }
        $usuario = new Usuarios();
        $form = $this->createForm('usuario', $usuario);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            try {
                $this->get('usuario_service')->encodePassword($usuario);
                $em->persist($usuario);
                $em->flush();
                $this->get('session')->getFlashBag()->add(
                        'usuario', 'Registro grabado satisfactoriamente'
                );
            } catch (Doctrine\DBAL\DBALException $e) {
                $this->get('session')->getFlashBag()->add(
                        'usuario', 'Ocurrio un error al grabar el registro'
                );
            }
            $nextAction = $form->get('saveAndAdd')->isClicked() ? '_admin_user_add' : '_admin_user_list';
            return $this->redirect($this->generateUrl($nextAction));
        }
        return array(
            'form' => $form->createView()
        );
    }

    /**
     * @Route("/user/{pk}", name="_admin_user_edit")
     * @Template("")
     */
    public function editUserAction(Request $request, $pk) {
        if (!$this->get('usuario_service')->hasPermission('usuario', 'edit')) {
            throw $this->createNotFoundException();
        }
        $usuario = $this->getDoctrine()
                        ->getRepository('IneiAuthBundle:Usuarios')->find($pk);
        $form = $this->createForm('usuario', $usuario);
        $form->handleRequest($request);

        if ($form->isValid()) {
            try{
            $em = $this->getDoctrine()->getManager();
            $this->get('usuario_service')->encodePassword($usuario);
            $em->persist($usuario);
            $em->flush();
            $this->get('session')->getFlashBag()->add(
                    'usuario', 'Registro modificado satisfactoriamente'
            );
            }catch(Doctrine\DBAL\DBALException $e){
                $this->get('session')->getFlashBag()->add(
                        'usuario', 'Ocurrio un error al modificar el registro'
                );
            }
            $nextAction = $form->get('saveAndAdd')->isClicked() ? '_admin_user_add' : '_admin_user_list';
            return $this->redirect($this->generateUrl($nextAction));
        }
        return array(
            'form' => $form->createView()
        );
    }

    /*     * **********************************ROLES************************************* */

    /**
     * @Route("/role", name="_admin_role_list")
     * @Template("")
     */
    public function listRoleAction(Request $request) {
        if (!$this->get('usuario_service')->hasPermission('rol', 'query')) {
            throw $this->createNotFoundException();
        }
        $criteria = array();
//        $criteria = $form->getData() ? $form->getData() : array();
//        foreach ($criteria as $key => $value) {
//            if (!$value) {
//                unset($criteria[$key]);
//            }
//        }
        $em = $this->getDoctrine()
                ->getRepository('IneiAuthBundle:Role');
        $query = $em->findBy($criteria);
        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $query, $this->get('request')->query->get('page', 1)/* page number */, 15/* limit per page */
        );


        return array(
            'pagination' => $pagination,
                //'form' => $form->createView()
        );
    }

    /**
     * @Route("/role/add", name="_admin_role_add")
     * @Template("")     
     */
    public function addRoleAction(Request $request) {
        if (!$this->get('usuario_service')->hasPermission('rol', 'add')) {
            throw $this->createNotFoundException();
        }
        $object = new Role();
        $form = $this->createForm('role', $object);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $conn = $this->get('database_connection');
            try {
                $conn->beginTransaction();
                $em = $this->getDoctrine()->getManager();
                $permissions = $object->getPermissions()->toArray();
                $object->getPermissions()->clear();
                $em->persist($object);
                $em->flush();
                foreach ($permissions as $item) {
                    $item->setRole($object);
                    $em->persist($item);
                }
                $em->flush();
                $this->get('session')->getFlashBag()->add(
                        'role', 'Registro grabado satisfactoriamente'
                );
                $conn->commit();
            } catch (DBALException $e) {
                $this->get('session')->getFlashBag()->add(
                        'role', 'Ocurrio un error al grabar el registro'
                );
                $conn->rollback();
            }
            $nextAction = $form->get('saveAndAdd')->isClicked() ? '_admin_role_add' : '_admin_role_list';
            return $this->redirect($this->generateUrl($nextAction));
        }
        return array(
            'form' => $form->createView()
        );
    }

    /**
     * @Route("/role/{pk}", name="_admin_role_edit")
     * @Template("")
     */
    public function editRoleAction(Request $request, $pk) {
        if (!$this->get('usuario_service')->hasPermission('rol', 'edit')) {
            throw $this->createNotFoundException();
        }
        $object = $this->getDoctrine()
                        ->getRepository('IneiAuthBundle:Role')->findOneCustomBy($pk);
        $form = $this->createForm('role', $object);
        $form->handleRequest($request);

        if ($form->isValid()) {
            try{
            $em = $this->getDoctrine()->getManager();
            $em->persist($object);
            $em->flush();
            if ($object->getRmpermissions()) {
                foreach ($object->getRmpermissions() as $value) {
                    $em->remove($value);
                }
                $em->flush();
            }
            $this->get('session')->getFlashBag()->add(
                    'role', 'Registro modificado satisfactoriamente'
            );
            }catch(Doctrine\DBAL\DBALException $e){
                $this->get('session')->getFlashBag()->add(
                        'role', 'Ocurrio un error al modificar el registro'
                );
            }
            $nextAction = $form->get('saveAndAdd')->isClicked() ? '_admin_role_add' : '_admin_role_list';
            return $this->redirect($this->generateUrl($nextAction));
        }
        return array(
            'form' => $form->createView()
        );
    }

}

src/Inei/Bundle/AuthBundle/Resources/views/SecurityCrud/addRole.html.twig
{% extends 'IneiAuthBundle:Secured:index.html.twig' %}
{% form_theme form.permissions 'IneiPayrollBundle:Form:form_table_horizontal_layout.html.twig' %}
{% block form %}
<div class="span10">
    {{ form_start(form) }}
    <div class="modal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Registrar Rol</h3>
        </div>
        <div class="modal-body">
        {% for flashMessage in app.session.flashbag.get('role') %}
            <div class="alert alert-{% if 'error' in flashMessage %}error{% else %}success{% endif %}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ flashMessage }}
            </div>
        {% endfor %}
        {{ form_errors(form) }}
            <div class="row-fluid">
                <div class="span1">
                    {{ form_label(form.name) }}
                </div>
                <div class="span2">
                    {{ form_errors(form.name) }}
                    {{ form_widget(form.name) }}
                </div>
                <div class="span1">
                    {{ form_label(form.role) }}
                </div>
                <div class="span2">
                    {{ form_errors(form.role) }}
                    {{ form_widget(form.role) }}
                </div>
            </div>
          <div class="folio-options"></div>
            <br>
            <table id="tfolios" class="table-bordered table-condensed">
                <thead>
                <th>Modulo</th><th>Permisos</th><th>Opciones</th>
                </thead>
                <tbody data-prototype="{{ form_widget(form.permissions.vars.prototype)|e }}"
                       data-options =''>
                    {% for item in form.permissions %}
                    <tr>
                        <td>{{ form_errors(item.module) }}{{ form_widget(item.module) }}</td>
                        <td>{{ form_errors(item.type) }}{{ form_widget(item.type) }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>  
          </div>
            <div class="modal-footer">
                {{ form_widget(form.save) }}
                {{ form_widget(form.saveAndAdd) }}
                <a href="{{ path('_admin') }}" class="btn">Cerrar</a>
            </div>            
        </div>
        {{ form_end(form) }}
</div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $('form').on('submit', function(e){
            return confirm('¿Esta seguro que desea guardar este registro?');
        });
        var collectionHolder = $('#tfolios tbody');
        var options = $('div.folio-options');
        var $addTagLink = $('<a href="#" class="btn btn-primary">Agregar Modulo</a>');

        jQuery(document).ready(function() {
            // add the "add a tag" anchor and li to the tags ul
            collectionHolder.find('tr').each(function() {
                addOptions($(this));
            });    
            options.append($addTagLink);
            
            collectionHolder.data('index', collectionHolder.find('tr').length);            
            $addTagLink.on('click', function(e) {
                e.preventDefault();
                addForm(collectionHolder);
            });
        });
        
        function addForm(collectionHolder) {
            var prototype = collectionHolder.data('prototype');
            var index = collectionHolder.data('index');
            var newForm = prototype.replace(/__name__/g, index);
            var $newForm = $(newForm);
            addOptions($newForm);
            collectionHolder.data('index', index + 1);
            collectionHolder.append($newForm);
        }
        
        function addOptions($newForm) {
            var $deleteopt = $('<a href="#" title="Eliminar Modulo"><i class="icon-trash"></i> </a>');
            var $options = $('<td></td>');            
            $options.append($deleteopt);
            $newForm.append($options);
            $deleteopt.on('click', function(e) {
                // prevent the link from creating a "#" on the URL
                e.preventDefault();
                // remove the li for the tag form
                $newForm.remove();
            });
        }
        
    </script>
{% endblock %}

src/Inei/Bundle/AuthBundle/Resources/views/SecurityCrud/addUser.html.twig
{% extends 'IneiAuthBundle:Secured:index.html.twig' %}
{% block form %}
<div class="span10">
    {{ form_start(form) }}
    <div class="modal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Registrar Usuario</h3>
        </div>
        <div class="modal-body">
        {% for flashMessage in app.session.flashbag.get('usuario') %}
            <div class="alert alert-{% if 'error' in flashMessage %}error{% else %}success{% endif %}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ flashMessage }}
            </div>
        {% endfor %}
        {{ form_errors(form) }}
            <div class="row-fluid">
                <div class="span1">
                    {{ form_label(form.nombres) }}
                </div>
                <div class="span3">
                    {{ form_errors(form.nombres) }}
                    {{ form_widget(form.nombres) }}
                </div>
                <div class="span1">
                    {{ form_label(form.email) }}
                </div>
                <div class="span2">
                    {{ form_errors(form.email) }}
                    {{ form_widget(form.email) }}
                </div>
            </div>
            <div class="row-fluid">
                <div class="span1">
                    {{ form_label(form.username) }}                    
                </div>
                <div class="span3">
                    {{ form_errors(form.username) }}
                    {{ form_widget(form.username) }}
                </div>
                <div class="span1">
                    {{ form_label(form.password) }}
                </div>
                <div class="span2">
                    {{ form_errors(form.password) }}
                    {{ form_widget(form.password) }}
                </div>                
                <div class="span1">
                    {{ form_label(form.isActive) }}                    
                </div>
                <div class="span2">
                    {{ form_errors(form.isActive) }}
                    {{ form_widget(form.isActive) }}
                </div>
            </div>
            <div class="row-fluid">
                <div class="span1">
                    {{ form_label(form.rolesCollection) }}
                </div>
                <div class="span8">
                    {{ form_errors(form.rolesCollection) }}
                    {{ form_widget(form.rolesCollection) }}
                </div>
            </div>
            </div>
            <div class="modal-footer">
                {{ form_widget(form.save) }}
                {{ form_widget(form.saveAndAdd) }}
                <a href="{{ path('_admin') }}" class="btn">Cerrar</a>
            </div>            
        </div>
        {{ form_end(form) }}
</div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $('form').on('submit', function(e){
            return confirm('¿Esta seguro que desea guardar este registro?');
        });
    </script>
{% endblock %}

src/Inei/Bundle/AuthBundle/Resources/views/SecurityCrud/editRole.html.twig
{% extends 'IneiAuthBundle:Secured:index.html.twig' %}
{% form_theme form.permissions 'IneiPayrollBundle:Form:form_table_horizontal_layout.html.twig' %}
{% block form %}
<div class="span10">
    {{ form_start(form) }}
    <div class="modal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Modificar Rol</h3>
        </div>
        <div class="modal-body">
        {% for flashMessage in app.session.flashbag.get('role') %}
            <div class="alert alert-{% if 'error' in flashMessage %}error{% else %}success{% endif %}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ flashMessage }}
            </div>
        {% endfor %}
        {{ form_errors(form) }}
            <div class="row-fluid">
                <div class="span1">
                    {{ form_label(form.name) }}
                </div>
                <div class="span2">
                    {{ form_errors(form.name) }}
                    {{ form_widget(form.name) }}
                </div>
                <div class="span1">
                    {{ form_label(form.role) }}
                </div>
                <div class="span2">
                    {{ form_errors(form.role) }}
                    {{ form_widget(form.role) }}
                </div>
            </div>
            <div class="folio-options"></div>
            <br>
            <table id="tfolios" class="table-bordered table-condensed">
                <thead>
                <th>Modulo</th><th>Permisos</th><th>Opciones</th>
                </thead>
                <tbody data-prototype="{{ form_widget(form.permissions.vars.prototype)|e }}"
                       data-options =''>
                    {% for item in form.permissions %}
                    <tr>
                        <td>{{ form_errors(item.module) }}{{ form_widget(item.module) }}</td>
                        <td>{{ form_errors(item.type) }}{{ form_widget(item.type) }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>  
          </div>
            <div class="modal-footer">
                {{ form_widget(form.save) }}
                {{ form_widget(form.saveAndAdd) }}
                <a href="{{ path('_admin') }}" class="btn">Cerrar</a>
            </div>            
        </div>
        {{ form_end(form) }}
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#role_role').attr('readonly', 'readonly');
    });
    $('form').on('submit', function(e){
        return confirm('¿Esta seguro que desea guardar este registro?');
    });
    
    var collectionHolder = $('#tfolios tbody');
        var options = $('div.folio-options');
        var $addTagLink = $('<a href="#" class="btn btn-primary">Agregar Modulo</a>');

        jQuery(document).ready(function() {
            // add the "add a tag" anchor and li to the tags ul
            collectionHolder.find('tr').each(function() {
                addOptions($(this));
            });    
            options.append($addTagLink);
            
            collectionHolder.data('index', collectionHolder.find('tr').length);            
            $addTagLink.on('click', function(e) {
                e.preventDefault();
                addForm(collectionHolder);
            });
        });
        
        function addForm(collectionHolder) {
            var prototype = collectionHolder.data('prototype');
            var index = collectionHolder.data('index');
            var newForm = prototype.replace(/__name__/g, index);
            var $newForm = $(newForm);
            addOptions($newForm);
            collectionHolder.data('index', index + 1);
            collectionHolder.append($newForm);
        }
        
        function addOptions($newForm) {
            var $deleteopt = $('<a href="#" title="Eliminar Modulo"><i class="icon-trash"></i> </a>');
            var $options = $('<td></td>');            
            $options.append($deleteopt);
            $newForm.append($options);
            $deleteopt.on('click', function(e) {
                // prevent the link from creating a "#" on the URL
                e.preventDefault();
                // remove the li for the tag form
                $newForm.remove();
            });
        }
</script>
{% endblock %}

src/Inei/Bundle/AuthBundle/Resources/views/SecurityCrud/editUser.html.twig
{% extends 'IneiAuthBundle:Secured:index.html.twig' %}
{% block form %}
<div class="span10">
    {{ form_start(form) }}
    <div class="modal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Modificar Usuario</h3>
        </div>
        <div class="modal-body">
        {% for flashMessage in app.session.flashbag.get('usuario') %}
            <div class="alert alert-{% if 'error' in flashMessage %}error{% else %}success{% endif %}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ flashMessage }}
            </div>
        {% endfor %}
        {{ form_errors(form) }}
            <div class="row-fluid">
                <div class="span1">
                    {{ form_label(form.nombres) }}
                </div>
                <div class="span3">
                    {{ form_errors(form.nombres) }}
                    {{ form_widget(form.nombres) }}
                </div>
                <div class="span1">
                    {{ form_label(form.email) }}
                </div>
                <div class="span2">
                    {{ form_errors(form.email) }}
                    {{ form_widget(form.email) }}
                </div>
            </div>
            <div class="row-fluid">
                <div class="span1">
                    {{ form_label(form.username) }}                    
                </div>
                <div class="span3">
                    {{ form_errors(form.username) }}
                    {{ form_widget(form.username) }}
                </div>
                <div class="span1">
                    {{ form_label(form.password) }}
                </div>
                <div class="span2">
                    {{ form_errors(form.password) }}
                    {{ form_widget(form.password) }}
                </div>                
                <div class="span1">
                    {{ form_label(form.isActive) }}                    
                </div>
                <div class="span2">
                    {{ form_errors(form.isActive) }}
                    {{ form_widget(form.isActive) }}
                </div>
            </div>
            <div class="row-fluid">
                <div class="span1">
                    {{ form_label(form.rolesCollection) }}
                </div>
                <div class="span8">
                    {{ form_errors(form.rolesCollection) }}
                    {{ form_widget(form.rolesCollection) }}
                </div>
            </div>
            </div>
            <div class="modal-footer">
                {{ form_widget(form.save) }}
                {{ form_widget(form.saveAndAdd) }}
                <a href="{{ path('_admin') }}" class="btn">Cerrar</a>
            </div>            
        </div>
        {{ form_end(form) }}
</div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $('form').on('submit', function(e){
            return confirm('¿Esta seguro que desea modificar este registro?');
        });
    </script>
{% endblock %}